# Generated by Django 4.2.7 on 2024-03-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_remove_studentassessmentscore_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentQuestionScore',
        ),
    ]
